# See: https://raw.githubusercontent.com/grafana/loki/v2.9.4/clients/cmd/promtail/promtail-docker-config.yaml
server:
  http_listen_port: ${PROMTAIL_HTTP_PORT}
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail/positions.yaml

clients:
  - url: http://${PROMTAIL_LOKI_HOST}:${PROMTAIL_LOKI_PORT}/loki/api/v1/push

scrape_configs:
- job_name: flog_scrape
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s
      # filters:
      #   - name: label
      #     values: ["logging=promtail"]
  relabel_configs:
    - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
      target_label: 'service'
    - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
      target_label: 'project'
  pipeline_stages:
    - match:
        selector: '{service="traefik"}'
        stages:
          - json:
              expressions:
                extra:
# - job_name: system
#   static_configs:
#   - targets:
#       - localhost
#     labels:
#       job: varlogs
#       __path__: /var/log/*log