## STATIC CONFIGURATION
log:
  level: INFO
  format: json

accessLog:
  format: json

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
          permanent: "true"

  websecure:
    address: ":443"
  mysql:
    address: ":3306"

  metrics:
    address: :8082

metrics:
  prometheus:
    entryPoint: metrics

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /traefik-dynamic-config.yaml
