with-expecter: true
packages:
    github.com/adamkirk-stayaway/organisations/pkg/validation:
        # place your package-specific config here
        config:
            dir: "pkg/validation/test/mocks/"
            outpkg: mocks
        interfaces:
            # select the interfaces you want mocked
            Logger:
            Cacher: