logging:
  level: debug
  format: json

api:
  server:
    debug_errors_enabled: false
    port: 8080
    access_log:
      format: json
      enabled: true

db:
  driver: "mongodb"
  mongodb:
    # Comes from env in local, see docker-compose.yml
    # Needs to be present in config though, some weird viper behaviour i think
    uri: mongodb://user:pass@mongo:27017
    database: "organisations"

redis:
  host: "redis:6379"
  password: ""
  db: 0
  connection_retries: 3

municipalities:
  sync:
    max_processes: 10
    batch_size: 10
    countries:
      - "United Kingdom"