version: "3.4"

networks:
  stayaway-dev:

x-network:
  &network
  networks:
    - stayaway-dev

services:
  venues-api:
    profiles:
      - venues
      - venues-api
    <<: *network
    build:
      context: ${VENUES_DIR}
      target: dev
    environment:
      APP_COMMAND: api
      AIR_DEBUG: ${VENUES_AIR_DEBUG}
    working_dir: /app
    volumes:
      - "${VENUES_DIR}/:/app"
    labels:
      - "traefik.http.routers.venues-api.rule=Host(`${VENUES_HOST}`)"
      - "traefik.enable=true"
      - "traefik.http.routers.venues-api.entrypoints=websecure"
      - "traefik.http.services.venues-api.loadbalancer.server.port=${VENUES_HTTP_PORT}"
      - "traefik.http.routers.venues-api.tls=true"
